security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        database_users:
            entity: { class: AppBundle:User, property: email }

    firewalls:
        api:
          pattern:   ^/
          provider:  database_users
          stateless: true
          anonymous: true
          guard:
              authenticators:
                  - lexik_jwt_authentication.jwt_token_authenticator
          logout:
              path:   /api/logout

    access_control:
        - { path: ^/_wdt|_profiler, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/sign-up, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auto-login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
